import type { CharacterEpisode } from '../../types';

export const episodesResponse: CharacterEpisode[] = [
  {
    id: 6,
    name: 'Rick Potion #9',
    air_date: 'January 27, 2014',
    episode: 'S01E06',
    characters: [
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/38',
      'https://rickandmortyapi.com/api/character/58',
      'https://rickandmortyapi.com/api/character/82',
      'https://rickandmortyapi.com/api/character/83',
      'https://rickandmortyapi.com/api/character/92',
      'https://rickandmortyapi.com/api/character/155',
      'https://rickandmortyapi.com/api/character/175',
      'https://rickandmortyapi.com/api/character/179',
      'https://rickandmortyapi.com/api/character/181',
      'https://rickandmortyapi.com/api/character/216',
      'https://rickandmortyapi.com/api/character/234',
      'https://rickandmortyapi.com/api/character/239',
      'https://rickandmortyapi.com/api/character/249',
      'https://rickandmortyapi.com/api/character/251',
      'https://rickandmortyapi.com/api/character/271',
      'https://rickandmortyapi.com/api/character/293',
      'https://rickandmortyapi.com/api/character/338',
      'https://rickandmortyapi.com/api/character/343',
      'https://rickandmortyapi.com/api/character/394',
    ],
    url: 'https://rickandmortyapi.com/api/episode/6',
    created: '2017-11-10T12:56:34.339Z',
  },
  {
    id: 7,
    name: 'Raising Gazorpazorp',
    air_date: 'March 10, 2014',
    episode: 'S01E07',
    characters: [
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/59',
      'https://rickandmortyapi.com/api/character/151',
      'https://rickandmortyapi.com/api/character/168',
      'https://rickandmortyapi.com/api/character/211',
      'https://rickandmortyapi.com/api/character/230',
      'https://rickandmortyapi.com/api/character/258',
      'https://rickandmortyapi.com/api/character/329',
      'https://rickandmortyapi.com/api/character/376',
      'https://rickandmortyapi.com/api/character/401',
    ],
    url: 'https://rickandmortyapi.com/api/episode/7',
    created: '2017-11-10T12:56:34.441Z',
  },

  {
    id: 11,
    name: 'Ricksy Business',
    air_date: 'April 14, 2014',
    episode: 'S01E11',
    characters: [
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/7',
      'https://rickandmortyapi.com/api/character/35',
      'https://rickandmortyapi.com/api/character/47',
      'https://rickandmortyapi.com/api/character/58',
      'https://rickandmortyapi.com/api/character/88',
      'https://rickandmortyapi.com/api/character/180',
      'https://rickandmortyapi.com/api/character/181',
      'https://rickandmortyapi.com/api/character/210',
      'https://rickandmortyapi.com/api/character/216',
      'https://rickandmortyapi.com/api/character/251',
      'https://rickandmortyapi.com/api/character/282',
      'https://rickandmortyapi.com/api/character/295',
      'https://rickandmortyapi.com/api/character/308',
      'https://rickandmortyapi.com/api/character/326',
      'https://rickandmortyapi.com/api/character/327',
      'https://rickandmortyapi.com/api/character/331',
      'https://rickandmortyapi.com/api/character/333',
      'https://rickandmortyapi.com/api/character/344',
      'https://rickandmortyapi.com/api/character/362',
      'https://rickandmortyapi.com/api/character/389',
      'https://rickandmortyapi.com/api/character/395',
      'https://rickandmortyapi.com/api/character/405',
      'https://rickandmortyapi.com/api/character/423',
      'https://rickandmortyapi.com/api/character/435',
      'https://rickandmortyapi.com/api/character/436',
    ],
    url: 'https://rickandmortyapi.com/api/episode/11',
    created: '2017-11-10T12:56:34.850Z',
  },
  {
    id: 12,
    name: 'A Rickle in Time',
    air_date: 'July 26, 2015',
    episode: 'S02E01',
    characters: [
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/11',
      'https://rickandmortyapi.com/api/character/64',
      'https://rickandmortyapi.com/api/character/237',
      'https://rickandmortyapi.com/api/character/313',
      'https://rickandmortyapi.com/api/character/437',
      'https://rickandmortyapi.com/api/character/438',
      'https://rickandmortyapi.com/api/character/439',
      'https://rickandmortyapi.com/api/character/440',
    ],
    url: 'https://rickandmortyapi.com/api/episode/12',
    created: '2017-11-10T12:56:34.953Z',
  },
  {
    id: 13,
    name: 'Mortynight Run',
    air_date: 'August 2, 2015',
    episode: 'S02E02',
    characters: [
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/23',
      'https://rickandmortyapi.com/api/character/28',
      'https://rickandmortyapi.com/api/character/34',
      'https://rickandmortyapi.com/api/character/106',
      'https://rickandmortyapi.com/api/character/122',
      'https://rickandmortyapi.com/api/character/129',
      'https://rickandmortyapi.com/api/character/131',
      'https://rickandmortyapi.com/api/character/133',
      'https://rickandmortyapi.com/api/character/136',
      'https://rickandmortyapi.com/api/character/174',
      'https://rickandmortyapi.com/api/character/180',
      'https://rickandmortyapi.com/api/character/196',
      'https://rickandmortyapi.com/api/character/207',
      'https://rickandmortyapi.com/api/character/242',
      'https://rickandmortyapi.com/api/character/257',
      'https://rickandmortyapi.com/api/character/282',
      'https://rickandmortyapi.com/api/character/309',
      'https://rickandmortyapi.com/api/character/311',
      'https://rickandmortyapi.com/api/character/362',
      'https://rickandmortyapi.com/api/character/386',
      'https://rickandmortyapi.com/api/character/393',
      'https://rickandmortyapi.com/api/character/436',
      'https://rickandmortyapi.com/api/character/441',
      'https://rickandmortyapi.com/api/character/442',
      'https://rickandmortyapi.com/api/character/443',
      'https://rickandmortyapi.com/api/character/444',
      'https://rickandmortyapi.com/api/character/445',
      'https://rickandmortyapi.com/api/character/446',
      'https://rickandmortyapi.com/api/character/447',
      'https://rickandmortyapi.com/api/character/448',
      'https://rickandmortyapi.com/api/character/449',
      'https://rickandmortyapi.com/api/character/450',
      'https://rickandmortyapi.com/api/character/451',
    ],
    url: 'https://rickandmortyapi.com/api/episode/13',
    created: '2017-11-10T12:56:35.055Z',
  },
  {
    id: 14,
    name: 'Auto Erotic Assimilation',
    air_date: 'August 9, 2015',
    episode: 'S02E03',
    characters: [
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/36',
      'https://rickandmortyapi.com/api/character/50',
      'https://rickandmortyapi.com/api/character/90',
      'https://rickandmortyapi.com/api/character/188',
      'https://rickandmortyapi.com/api/character/249',
      'https://rickandmortyapi.com/api/character/301',
      'https://rickandmortyapi.com/api/character/336',
      'https://rickandmortyapi.com/api/character/355',
      'https://rickandmortyapi.com/api/character/372',
    ],
    url: 'https://rickandmortyapi.com/api/episode/14',
    created: '2017-11-10T12:56:35.158Z',
  },
  {
    id: 15,
    name: 'Total Rickall',
    air_date: 'August 16, 2015',
    episode: 'S02E04',
    characters: [
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/16',
      'https://rickandmortyapi.com/api/character/31',
      'https://rickandmortyapi.com/api/character/32',
      'https://rickandmortyapi.com/api/character/76',
      'https://rickandmortyapi.com/api/character/109',
      'https://rickandmortyapi.com/api/character/128',
      'https://rickandmortyapi.com/api/character/141',
      'https://rickandmortyapi.com/api/character/154',
      'https://rickandmortyapi.com/api/character/169',
      'https://rickandmortyapi.com/api/character/236',
      'https://rickandmortyapi.com/api/character/244',
      'https://rickandmortyapi.com/api/character/248',
      'https://rickandmortyapi.com/api/character/259',
      'https://rickandmortyapi.com/api/character/262',
      'https://rickandmortyapi.com/api/character/280',
      'https://rickandmortyapi.com/api/character/324',
      'https://rickandmortyapi.com/api/character/329',
      'https://rickandmortyapi.com/api/character/352',
      'https://rickandmortyapi.com/api/character/391',
    ],
    url: 'https://rickandmortyapi.com/api/episode/15',
    created: '2017-11-10T12:56:35.261Z',
  },
  {
    id: 16,
    name: 'Get Schwifty',
    air_date: 'August 23, 2015',
    episode: 'S02E05',
    characters: [
      'https://rickandmortyapi.com/api/character/1',
      'https://rickandmortyapi.com/api/character/2',
      'https://rickandmortyapi.com/api/character/3',
      'https://rickandmortyapi.com/api/character/4',
      'https://rickandmortyapi.com/api/character/5',
      'https://rickandmortyapi.com/api/character/24',
      'https://rickandmortyapi.com/api/character/47',
      'https://rickandmortyapi.com/api/character/115',
      'https://rickandmortyapi.com/api/character/124',
      'https://rickandmortyapi.com/api/character/138',
      'https://rickandmortyapi.com/api/character/161',
      'https://rickandmortyapi.com/api/character/162',
      'https://rickandmortyapi.com/api/character/172',
      'https://rickandmortyapi.com/api/character/182',
      'https://rickandmortyapi.com/api/character/199',
      'https://rickandmortyapi.com/api/character/212',
      'https://rickandmortyapi.com/api/character/213',
      'https://rickandmortyapi.com/api/character/240',
      'https://rickandmortyapi.com/api/character/241',
      'https://rickandmortyapi.com/api/character/253',
      'https://rickandmortyapi.com/api/character/255',
      'https://rickandmortyapi.com/api/character/272',
      'https://rickandmortyapi.com/api/character/309',
      'https://rickandmortyapi.com/api/character/329',
      'https://rickandmortyapi.com/api/character/331',
      'https://rickandmortyapi.com/api/character/344',
      'https://rickandmortyapi.com/api/character/346',
      'https://rickandmortyapi.com/api/character/347',
      'https://rickandmortyapi.com/api/character/395',
      'https://rickandmortyapi.com/api/character/452',
      'https://rickandmortyapi.com/api/character/454',
    ],
    url: 'https://rickandmortyapi.com/api/episode/16',
    created: '2017-11-10T12:56:35.364Z',
  },
];
